// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://keyhmcgjmkjlwbycqhjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtleWhtY2dqbWtqbHdieWNxaGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxNzI3MTAsImV4cCI6MjA4Mjc0ODcxMH0.0xD1rqn49H01p2Cm6N2sgqC3n2fFVEvB063RcaUpEKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);